AJAXtwitter/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :feed, only: [:show]
  resource :session, only: [:create, :destroy, :new]
  resources :tweets, only: [:create]
  resources :users, only: [:create, :new, :show] do
    get 'search', on: :collection

    resource :follow, only: [:create, :destroy]
  end

  root to: redirect('/feed')
end

AJAXtwitter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

AJAXtwitter/app/models/follow.rb
class Follow < ApplicationRecord
  validates :follower, uniqueness: { scope: :followee }

  belongs_to :followee,
    class_name: :User

  belongs_to :follower,
    class_name: :User
end

AJAXtwitter/app/models/mention.rb
class Mention < ApplicationRecord
  validates :user, uniqueness: { scope: :tweet }

  belongs_to :tweet
  belongs_to :user
end

AJAXtwitter/app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  has_many :mentions

  has_many :mentioned_users,
    through: :mentions,
    source: :user
end

AJAXtwitter/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :in_follows,
    foreign_key: :followee_id,
    class_name: :Follow

  has_many :out_follows,
    foreign_key: :follower_id,
    class_name: :Follow

  has_many :followers,
    through: :in_follows,
    source: :follower

  has_many :followees,
    through: :out_follows,
    source: :followee

  has_many :tweets, dependent: :destroy

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    # no user with given username
    return nil if user.nil?

    # check user's password
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  end

  def feed_tweets(limit = nil, max_created_at = nil)
    @tweets = Tweet
      .joins(:user)
      .joins('LEFT OUTER JOIN follows ON users.id = follows.followee_id')
      .where('tweets.user_id = :id OR follows.follower_id = :id', id: self.id)
      .order('tweets.created_at DESC')
      .distinct

    # TODO: How can we use limit/max_created_at here??

    @tweets
  end

  def followed_user_ids
    @followed_user_ids ||= out_follows.pluck(:followee_id)
  end

  def follows?(user)
    followed_user_ids.include?(user.id)
  end
end

AJAXtwitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  
  def current_user
    # fetches the user we've logged in as
    return nil if self.session[:session_token].nil?
    User.find_by(session_token: self.session[:session_token])
  end

  def log_in!(user)
    # force other clients to log out by regenerating token
    user.reset_session_token!
    # log this client in
    self.session[:session_token] = user.session_token
  end

  def log_out!
    self.session[:session_token] = nil
  end

  def require_logged_in!
    redirect_to new_session_url if current_user.nil?
  end

  def require_not_logged_in!
    redirect_to feed_url unless current_user.nil?
  end
end

AJAXtwitter/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :require_logged_in!

  LIMIT = 20

  def show
    @feed_tweets =
      current_user.feed_tweets(LIMIT, params[:max_created_at]).includes(:user)

    render :show
  end
end

AJAXtwitter/app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.create!(followee_id: params[:user_id])

    respond_to do |format|
      format.json { render json: @follow }
      format.html { redirect_to request.referrer }
    end
  end

  def destroy
    # simulate latency
    sleep(1)

    @follow = current_user.out_follows.find_by(followee_id: params[:user_id])
    @follow.destroy!

    respond_to do |format|
      format.json { render json: @follow }
      format.html { redirect_to request.referrer }
    end
  end
end

AJAXtwitter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:destroy]

  def create
    # signs a user in
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      # no user with the given name!
      flash.now[:errors] = ['Invalid credentials']
      render :new
    else
      # sign the user in
      log_in!(@user)
      redirect_to feed_url
    end
  end

  def destroy
    # sign a user out
    log_out!
    redirect_to new_session_url
  end

  def new
    # presents a login form
    render :new
  end
end

AJAXtwitter/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_logged_in!

  def create
    # simulate latency
    sleep(1)

    @tweet = current_user.tweets.build(tweet_params)

    if @tweet.save
      # redirect_to request.referrer
      respond_to do |format|
        format.html { render :show }
        format.json { render :show }
      end
    else
      # Lazy: even respond with JSON to invalid HTML request.
      render json: @tweet.errors.full_messages, status: 422
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:content, mentioned_user_ids: [])
  end
end

AJAXtwitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_not_logged_in!, only: [:create, :new]
  before_action :require_logged_in!, only: [:show]

  def create
    # sign up the user
    @user = User.new(user_params)
    if @user.save
      # redirect them to the new user's show page
      log_in!(@user)
      redirect_to feed_url
    else
      # input didn't pass validation; re-render sign up form.
      render :new
    end
  end

  def new
    # present form for signup
    @user = User.new # dummy user object
    render :new
  end

  def show
    if current_user.nil?
      # let them log in
      redirect_to new_session_url
      return
    end

    @user = User.includes(tweets: :mentioned_users).find(params[:id])
    render :show
  end

  def search
    if params[:query].present?
      @users = User.where('username ~ ?', params[:query])
    else
      @users = User.none
    end

    respond_to do |format|
      format.html { render :search }
      format.json { render :search }
    end
  end

  protected
  def user_params
    self.params.require(:user).permit(:username, :password)
  end
end

AJAXtwitter/app/helpers/application_helper.rb
module ApplicationHelper
end

AJAXtwitter/app/views/feeds/show.html.erb
<h1>Welcome <%= current_user.username %>!</h1>

<b>Your Feed!</b>
<ul id="feed">
  <% @feed_tweets.each do |tweet| %>
    <li><%= render 'tweets/tweet', tweet: tweet %></li>
  <% end %>
</ul>

<%= render 'tweets/form' %>

AJAXtwitter/app/views/follows/_form.html.erb
<% follows = current_user.follows?(user) %>
<button class="follow-toggle" data-user_id="<%= user.id %>" data-user-initial-follow-state="<%= follows %>" type="button" name="button"></button>

AJAXtwitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <ul>
      <li><a href="<%= feed_url %>">Feed</a></li>
      <li><a href="<%= search_users_url %>">User Search</a></li>
    </ul>

    <% if current_user %>
      <form action="/session" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">

        <input type="submit" value="Logout!">
      </form>
    <% end %>
    
    <%= yield %>
  </body>
</html>

AJAXtwitter/app/views/tweets/_form.html.erb
<h2>New Tweet!</h2>
<form class="tweet-compose" action="/tweets" method="POST">
  <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

  <label>
    Content
    <textarea name="tweet[content]"></textarea>
  </label>
  <br>

  <label>
    Mention
    <select name="tweet[mentioned_user_ids][]">
      <option></option>
      <% User.all.each do |user| %>
        <option value="<%= user.id %>"><%= user.username %></option>
      <% end %>
    </select>
  </label>
  <br>

  <input type="Submit" value="Post Tweet!">
</form>

AJAXtwitter/app/views/tweets/_tweet.html.erb
<%= tweet.content %>
-- <a href="<%= user_url(tweet.user.id) %>"><%= tweet.user.username %></a>
-- <%= tweet.created_at %>

<% if tweet.mentioned_users.length > 0 %>
  <ul>
    <% tweet.mentioned_users.each do |mentioned_user| %>
      <li><a href="<%= user_url(mentioned_user) %>"><%= mentioned_user.username %></a></li>
    <% end %>
  </ul>
<% end %>

AJAXtwitter/app/views/users/new.html.erb
<h1>Sign up!</h1>

<ul>
  <% @user.errors.full_messages.each do |err_msg| %>
    <li><%= err_msg %></li>
  <% end %>
</ul>

<form action="/users" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
    type="text"
    name="user[username]"
    id="user_username"
    value="<%= @user.username %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password">
  <br>

  <input type="submit" value="Create User!">
</form>

<a href="<%= new_session_url %>">Already have an account? Log In</a>

AJAXtwitter/app/views/users/search.html.erb
<h1>Search!</h1>

<nav class="users-search">
  <label for="">Search for a User
    <input type="text" name="user[username]" value="" placeholder="Enter Username">
  </label>
  
  <!-- <input type="submit" value="Search"> -->
  
  <label for="">Results
    <ul class="users">
      
    </ul>
  </label>
</nav>

<!-- <ul>
  <% @users.each do |user| %>
    <li>
      <a href="<%= user_url(user) %>"><%= user.username %></a>
      <%= render 'follows/form', user: user %>
    </li>
  <% end %>
</ul> -->

AJAXtwitter/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= render 'follows/form', user: @user %>

<b>Tweets</b>
<ul>
  <% @user.tweets.each do |tweet| %>
    <li><%= render 'tweets/tweet', tweet: tweet %></li>
  <% end %>
</ul>

<b>Followers</b>
<ul>
  <% @user.followers.each do |follower| %>
    <li><%= follower.username %></li>
  <% end %>
</ul>

<b>Followees</b>
<ul>
  <% @user.followees.each do |followee| %>
    <li><%= followee.username %></li>
  <% end %>
</ul>